
##################################
#joint constraint
##################################

joint_constraint_limits:
  arm_left_1_joint: 
    ceneter_position: 0.0 
    tolerance_above: 0.47
    tolerance_below:  1.70
  arm_left_2_joint:
    ceneter_position: 0
    tolerance_above: 1.50
    tolerance_below: 0.20
  arm_left_3_joint:
    ceneter_position: -1.00
    tolerance_above: 1.30
    tolerance_below: 0.65
#  arm_left_4_joint:
#    ceneter_position: -3.14
#    tolerance_above: 1.57
#    tolerance_below: 3.14
#  arm_left_5_joint:
#    ceneter_position: -1.5
#    tolerance_above: 1.03
#    tolerance_below: 1.15
  arm_left_6_joint:
    ceneter_position: -1.15
    tolerance_above: 1.0
    tolerance_below: 1.0
  arm_left_7_joint:
    ceneter_position: 0
    tolerance_above: 0.35
    tolerance_below: 3.00

# ---- arm_right -----

  arm_right_1_joint:
    ceneter_position: -0.5
    tolerance_above: 2.0
    tolerance_below: 2.0
#  arm_right_2_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0
#  arm_right_3_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0
#  arm_right_4_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0
#  arm_right_5_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0
  arm_right_6_joint:
    ceneter_position: 0
    tolerance_above: 2.0
    tolerance_below: 2.0
  arm_right_7_joint:
    ceneter_position: 0
    tolerance_above: 5.5
    tolerance_below: 5.5
  
##################################
#position constraint --> check what required
##################################

#position_constraint_limits:
#  arm_elbow_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0
#  arm_shoulder_lift_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0
#  arm_shoulder_pan_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0
#  arm_wrist_1_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0
#  arm_wrist_2_joint:
#    ceneter_position: -1.5
#    tolerance_above: 0.7652
#    tolerance_below: 1.15
#  arm_wrist_3_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0

##################################
#orientation constraint --> check what required
##################################

#joint_constraint_limits:
#  arm_elbow_joint:
#    ceneter_position: -0.675
#    tolerance_above: 0.785
#    tolerance_below: 1.05
#  arm_shoulder_lift_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0
#  arm_shoulder_pan_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0
#  arm_wrist_1_joint:
#    ceneter_position: -3.14
#    tolerance_above: 1.57
#    tolerance_below: 3.14
#  arm_wrist_2_joint:
#    ceneter_position: -1.5
#    tolerance_above: 0.7652
#    tolerance_below: 1.15
#  arm_wrist_3_joint:
#    ceneter_position: 0
#    tolerance_above: 0
#    tolerance_below: 0

